// src/pages/projects/index.vue
<template>
	<div class="flex items-center flex-col px-4 bg-base-200">
		<div v-for="(project, index) in projects" :key="project.name + '_' + index" class="w-1/2 m-4">
			<router-link :to="/projects/ + project.name">
				<div class="card bg-base-300 hover:shadow-md">
					<div class="card-body">
						<h2 class="card-title">
							<span class="font-extralight"
								>{{ project.owner.login }}/<span class="font-bold">{{ project.name }}</span></span
							>
							<div v-if="project.fork" class="badge badge-primary">FORK</div>
						</h2>
						<p>{{ project.description }}</p>
						<div>
							<div class="card-actions justify-end pt-1">
								<div class="badge badge-secondary rounded mr-auto">
									Updated
									{{ timestamp.format(Date.now() - new Date(project.updated_at).getTime(), 1) }} ago
								</div>
								<div class="badge badge-info rounded">{{ project.stargazers_count }} Stars</div>
								<div class="badge badge-info rounded">{{ project.watchers_count }} Watchers</div>
							</div>
							<div class="card-actions">
								<div v-if="project.language" class="badge badge-error rounded mt-1">
									{{ project.language }}
								</div>
								<div v-if="project.license" class="badge badge-success rounded ml-auto mt-1">
									{{ project.license.name }}
								</div>
							</div>
						</div>
					</div>
				</div>
			</router-link>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Project } from '~/types/Project';
import { DurationFormatter } from '@sapphire/time-utilities';
import { useFetch } from '~/util';

export default defineComponent({
	data() {
		return {
			projects: new Array<Project>(),
			timestamp: new DurationFormatter(),
		};
	},
	async created() {
		await this.getProjects();
	},
	methods: {
		async getProjects() {
			const data = await useFetch<Project[]>('/projects');

			this.projects = data
				.sort((x, y) => {
					return Number(x.fork) - Number(y.fork);
				})
				.filter((project) => {
					return project.description && project.full_name.toLowerCase() !== 'megatank58/megatank58';
				});
		},
	},
});
</script>

// src/routes/projects/index.svelte
<script context="module" lang="ts">
	export async function load() {
		const url = `https://bd.megatank58.me/projects`;
		const response = await fetch(url);
		const data: Project[] = (await response.json())
			.sort((x: Project, y: Project) => {
				return (
					Date.now() -
					new Date(x.updated_at).getTime() -
					(Date.now() - new Date(y.updated_at).getTime())
				);
			})
			.filter((project: Project) => {
				return project.description && project.full_name.toLowerCase() !== 'megatank58/megatank58';
			});

		return {
			status: response.status,
			props: {
				projects: data
			}
		};
	}
</script>

<script lang="ts">
	import { DurationFormatter } from '@sapphire/time-utilities';
	import type { Project } from 'src/types/Project';

	const duration = new DurationFormatter();
	export let projects: Project[];
</script>

<div class="flex items-center flex-col px-4 bg-base-200">
	{#each projects as { name, description, owner: { login }, updated_at, language, fork, license }}
		<div class="sm:w-1/2 w-full m-4">
			<a href={'/projects/' + name}>
				<div class="card bg-base-300 hover:shadow-md">
					<div class="card-body">
						<h2 class="card-title">
							<span class="font-extralight">{login}/<span class="font-bold">{name}</span></span>
							{#if fork}
								<svg
									xmlns="http://www.w3.org/2000/svg"
									xmlns:xlink="http://www.w3.org/1999/xlink"
									width="1em"
									height="1em"
									viewBox="0 0 512 512"
									><path
										fill="currentColor"
										d="M124 166.291v179.418a76 76 0 1 0 32 0V282h152a80.091 80.091 0 0 0 80-80v-36.689a75.983 75.983 0 1 0-32 1.733V202a48.055 48.055 0 0 1-48 48H156v-83.709a76 76 0 1 0-32 0ZM324 92a44 44 0 1 1 44 44a44.049 44.049 0 0 1-44-44ZM184 420a44 44 0 1 1-44-44a44.049 44.049 0 0 1 44 44ZM140 48a44 44 0 1 1-44 44a44.049 44.049 0 0 1 44-44Z"
									/></svg
								>
							{/if}
						</h2>
						<p>{description}</p>
						<div>
							<div class="card-actions justify-end pt-1">
								<div class="badge badge-success rounded mr-auto">
									Updated
									{duration.format(Date.now() - new Date(updated_at).getTime(), 1)} ago
								</div>
							</div>
							<div class="card-actions">
								<div class="badge badge-error rounded mt-1">
									{language ?? 'Markdown'}
								</div>
								<div v-if="project.license" class="badge badge-info rounded ml-auto mt-1">
									{license?.name ?? 'MIT License'}
								</div>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
	{/each}
</div>
