// src/routes/projects/[project].svelte
<script context="module" lang="ts">
	import { marked } from 'marked';
	import hljs from 'highlight.js';

	export async function load({ params }: { params: { project: string } }) {
		const url = `https://raw.githubusercontent.com/Megatank58/${params.project}/main/README.md`;
		const response = await fetch(url);

		marked.setOptions({
			highlight: function (code, lang) {
				const language = hljs.getLanguage(lang) ? lang : 'plaintext';
				return hljs.highlight(code, { language }).value;
			}
		});

		return {
			status: response.status,
			props: {
				readme: marked(await response.text())
			}
		};
	}
</script>

<script lang="ts">
	export let readme: string;
</script>

<div
	class="font-mono prose max-w-none m-4 p-2 sm:m-16 sm:p-4 rounded-lg shadow-lg border-t-2 border-l-4 border-neutral-focus prose-pre:p-3 prose-pre:rounded prose-pre:overflow-x-auto prose-a:text-primary prose-a:no-underline prose-img:inline prose-img:m-1 prose-p:m-1 prose-h1:my-4 prose-h1:border-b prose-h2:my-4 prose-h2:border-b"
>
	{@html readme}
</div>

// src/pages/projects/[project].vue
<template>
	<div
		class="
			prose
			max-w-none
			m-16
			p-4
			rounded-lg
			shadow-lg
			border-t-2 border-l-4 border-neutral-focus
			prose-pre:p-3 prose-pre:rounded prose-pre:overflow-x-auto
			prose-a:text-primary prose-a:no-underline
			prose-img:inline prose-img:m-1 prose-p:m-1 prose-h1:my-4 prose-h2:my-4
		"
		v-html="readme"
	></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue-demi';
import { parseMarkdown } from '~/util';

export default defineComponent({
	data() {
		return {
			readme: '',
		};
	},
	async created() {
		await this.getReadme();
	},
	methods: {
		async getReadme() {
			const text = await (
				await fetch('https://raw.githubusercontent.com/Megatank58/' + this.$route.params.project as string + '/main/README.md')
			).text();
			this.readme = parseMarkdown(text);
		},
	},
});
</script>
